import Head from "next/head"

import Layout from "../../components/Layout"
import Nav from "../../components/Nav"
import styles from '../../styles/Home.module.css'

export default function Timeline({userName}) {
    return (
        <div className={styles.container}>
        <Head>
          <title>Next App made to practice with this framework</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Nav></Nav>
        <Layout>
          <h1>
            This is timeline
          </h1>
          <h2>Name: {userName}</h2>
        </Layout>
      </div>
    )
}

// Timeline.getInitialProps = async () => {
//     return Promise.resolve({
//         userName: '@miadeveloper'
//     })
// }

Timeline.getInitialProps = async () => {
    return fetch('http://localhost:3000//api/hello')
        .then(res => res.json())
        .then(response => {
            const {userName} = response
            return {userName}
        })
}