import Head from "next/head"

import Layout from "../../components/Layout"
import Nav from "../../components/Nav"
import styles from '../../styles/Home.module.css'

export default function Timeline() {
    return (
        <div className={styles.container}>
        <Head>
          <title>Next App made to practice with this framework</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Nav></Nav>
        <Layout>
          <h1>
            This is timeline
          </h1>
        </Layout>
      </div>
    )

}