import Head from 'next/head'
import Link from 'next/link'

import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next App made to practice with this framework</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <ul>
            <li>
              <Link href="/">
                <a>Inicio</a>
              </Link>
            </li>
            <li>
              <Link href="/timeline">
                <a>Timeline</a>
              </Link>
            </li>
          </ul>
        </nav>
      </header>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>
      <style jsx>{
        `
        nav {
          width: 100%;
          position: fixed;
          background: #0070f3;
        }
        nav ul {
          width: 100%;
          justify-content: center;
          list-style-type: none;
          display: flex;
          margin: 0 auto;
          padding: 18px 0;
        }
        nav li {
          padding: 0 18px;
          color: #fff;
        }
        `
      }

      </style>
    </div>
  )
}
